# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'faq.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_newers(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(657, 493)
        Form.setStyleSheet("background-color:grey;")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 631, 471))
        self.textBrowser.setStyleSheet("background-color: black;")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(490, 440, 121, 31))
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Arial\'; font-size:14pt; font-weight:600; color:#ffffff; background-color:#000000;\">Магазины</span><span style=\" font-family:\'Arial\'; font-size:14pt; color:#ffffff; background-color:#000000;\"> - есть два вида, нелегальный (отмечены в виде человека с балаклавой) покупка осуществляется за грязный нал и легальный (в виде витрины) покупка осуществляется за наличные.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial\'; font-size:14pt; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"docs-internal-guid-adff627c-7fff-8f06-1c1b-033df1af4c77\"></a><span style=\" font-family:\'Arial\'; font-size:14pt; font-weight:600; color:#ffffff; background-color:#000000;\">У</span><span style=\" font-family:\'Arial\'; font-size:14pt; font-weight:600; color:#ffffff; background-color:#000000;\">правление</span><span style=\" font-family:\'Arial\'; font-size:14pt; color:#ffffff; background-color:#000000;\"> - базовую информацию об управлении игрок сможет найти открыв карту и в левом верхнем углу найти меню, если понадобится изменить то ESC - настройки - управление - настройки дополнения - Tactical Life.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Arial\'; font-size:14pt; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a name=\"docs-internal-guid-fea6d57f-7fff-b764-42d5-9ff596dd20d0\"></a><span style=\" font-family:\'Arial\'; font-size:14pt; font-weight:600; color:#ffffff; background-color:#000000;\">Л</span><span style=\" font-family:\'Arial\'; font-size:14pt; font-weight:600; color:#ffffff; background-color:#000000;\">айфхак</span><span style=\" font-family:\'Arial\'; font-size:14pt; color:#ffffff; background-color:#000000;\"> - если ты ненормальный и хочешь всего и сразу то беги(машины то у тебя нет хах) в магазин грузовиков покупай фуру на которую хватит денег, и едь в порт который находится в кавале (точнее рядом с ним есть РЦ), там берём доставку и едем куда нибудь (туда где рядом),таким образом ты получаешь деньги и тратиться только на бензин, возможно вы сможете найти таким образом знакомых но основная задача получить дэнег, теперь когда у тебя есть деньги ты можешь купить себе вертолет и заняться продажей (воровоные боеприпасы). Главное помни не лети туда если цена за упакованный ресурс ниже 18000.</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Закрыть"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
